---


- name: start docker container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image }}"
    state: started
    privileged: true
    volumes: "{{ docker_volumes }}"
    volume_driver: "{{ docker_volume_driver }}"
    keep_volumes: "{{ docker_keep_volumes }}"
    published_ports: "{{ docker_published_ports }}"
  become: yes
  become_method: sudo
  tags:
    - docker-containers
    - docker-containers-dam-api